import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from '../app/_components/Header.jsx'
import Footer from '../app/_components/Footer.jsx'
import MainStyles from '../app/_styles/MainStyles.jsx'

import "../app/_styles/async.css"
import "../app/_styles/critical.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <MainStyles/>
        <Header/>
        {children}
        <Footer/> 
      </body>
    </html>
  );
}
